export * from "@/api/admins/admins";
export * from "@/api/audit/audit";
export * from "@/api/auth/auth";
export * from "@/api/content/content";
export * from "@/api/dashboard/dashboard";
export * from "@/api/faq/faq";
export * from "@/api/kyc/kyc";
export * from "@/api/liens/liens";
export * from "@/api/platform/platform";
export * from "@/api/products/products";
export * from "@/api/rates/rates";
export * from "@/api/roi/roi";
export * from "@/api/savings/savings";
export * from "@/api/transactions/transactions";
export * from "@/api/treasury/treasury";
export * from "@/api/users/users";
export * from "@/api/wallet/wallet";

export { request, ENDPOINT } from "@/api/graphql-client";
export { createMutation, createQuery } from "@/api/factory";
export { queryKey, SCOPES, type Scope } from "@/api/query-keys";
export { APIError, isAPIError, type IResponse, type IPagination } from "@/types/api";
